# Generated by Django 3.2.1 on 2022-03-17 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('things', '0002_auto_20220317_1419'),
    ]

    operations = [
        migrations.AddField(
            model_name='usercard',
            name='image',
            field=models.ImageField(default='media/user/default.jpg', upload_to=''),
        ),
    ]
