# Generated by Django 3.2.1 on 2022-03-18 11:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('things', '0008_auto_20220318_1656'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='country_region',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='things.country_region'),
        ),
    ]
